/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as ConsultationsIndexRouteImport } from './routes/consultations.index'
import { Route as OpeningsIndexRouteImport } from './routes/openings.index'
import { Route as OpeningsOpeningIdRouteImport } from './routes/openings.$openingId'
import { Route as OpeningsNewRouteImport } from './routes/openings.new'
import { Route as QuestionsIndexRouteImport } from './routes/questions.index'
import { Route as QuestionsQuestionIdRouteImport } from './routes/questions.$questionId'
import { Route as QuestionsNewRouteImport } from './routes/questions.new'
import { Route as TrainersIndexRouteImport } from './routes/trainers.index'
import { Route as QuestionsQuestionIdEditRouteImport } from './routes/questions.$questionId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsIndexRoute = ConsultationsIndexRouteImport.update({
  id: '/consultations/',
  path: '/consultations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsIndexRoute = OpeningsIndexRouteImport.update({
  id: '/openings/',
  path: '/openings/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsOpeningIdRoute = OpeningsOpeningIdRouteImport.update({
  id: '/openings/$openingId',
  path: '/openings/$openingId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsNewRoute = OpeningsNewRouteImport.update({
  id: '/openings/new',
  path: '/openings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsQuestionIdRoute = QuestionsQuestionIdRouteImport.update({
  id: '/questions/$questionId',
  path: '/questions/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsNewRoute = QuestionsNewRouteImport.update({
  id: '/questions/new',
  path: '/questions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersIndexRoute = TrainersIndexRouteImport.update({
  id: '/trainers/',
  path: '/trainers/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsQuestionIdEditRoute = QuestionsQuestionIdEditRouteImport.update({
  id: '/questions/$questionId_/edit',
  path: '/questions/$questionId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/openings/$openingId': typeof OpeningsOpeningIdRoute
  '/openings/new': typeof OpeningsNewRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/questions/new': typeof QuestionsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/consultations/': typeof ConsultationsIndexRoute
  '/openings/': typeof OpeningsIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/trainers/': typeof TrainersIndexRoute
  '/questions/$questionId/edit': typeof QuestionsQuestionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/openings/$openingId': typeof OpeningsOpeningIdRoute
  '/openings/new': typeof OpeningsNewRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/questions/new': typeof QuestionsNewRoute
  '/admin': typeof AdminIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/consultations': typeof ConsultationsIndexRoute
  '/openings': typeof OpeningsIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/trainers': typeof TrainersIndexRoute
  '/questions/$questionId/edit': typeof QuestionsQuestionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/openings/$openingId': typeof OpeningsOpeningIdRoute
  '/openings/new': typeof OpeningsNewRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/questions/new': typeof QuestionsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/consultations/': typeof ConsultationsIndexRoute
  '/openings/': typeof OpeningsIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/trainers/': typeof TrainersIndexRoute
  '/questions/$questionId_/edit': typeof QuestionsQuestionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
    | '/openings/$openingId'
    | '/openings/new'
    | '/questions/$questionId'
    | '/questions/new'
    | '/admin/'
    | '/companies/'
    | '/consultations/'
    | '/openings/'
    | '/questions/'
    | '/trainers/'
    | '/questions/$questionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
    | '/openings/$openingId'
    | '/openings/new'
    | '/questions/$questionId'
    | '/questions/new'
    | '/admin'
    | '/companies'
    | '/consultations'
    | '/openings'
    | '/questions'
    | '/trainers'
    | '/questions/$questionId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
    | '/openings/$openingId'
    | '/openings/new'
    | '/questions/$questionId'
    | '/questions/new'
    | '/admin/'
    | '/companies/'
    | '/consultations/'
    | '/openings/'
    | '/questions/'
    | '/trainers/'
    | '/questions/$questionId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  OpeningsOpeningIdRoute: typeof OpeningsOpeningIdRoute
  OpeningsNewRoute: typeof OpeningsNewRoute
  QuestionsQuestionIdRoute: typeof QuestionsQuestionIdRoute
  QuestionsNewRoute: typeof QuestionsNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  ConsultationsIndexRoute: typeof ConsultationsIndexRoute
  OpeningsIndexRoute: typeof OpeningsIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  TrainersIndexRoute: typeof TrainersIndexRoute
  QuestionsQuestionIdEditRoute: typeof QuestionsQuestionIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations/': {
      id: '/consultations/'
      path: '/consultations'
      fullPath: '/consultations/'
      preLoaderRoute: typeof ConsultationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings/': {
      id: '/openings/'
      path: '/openings'
      fullPath: '/openings/'
      preLoaderRoute: typeof OpeningsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings/$openingId': {
      id: '/openings/$openingId'
      path: '/openings/$openingId'
      fullPath: '/openings/$openingId'
      preLoaderRoute: typeof OpeningsOpeningIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings/new': {
      id: '/openings/new'
      path: '/openings/new'
      fullPath: '/openings/new'
      preLoaderRoute: typeof OpeningsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$questionId': {
      id: '/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/questions/$questionId'
      preLoaderRoute: typeof QuestionsQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/new': {
      id: '/questions/new'
      path: '/questions/new'
      fullPath: '/questions/new'
      preLoaderRoute: typeof QuestionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/': {
      id: '/trainers/'
      path: '/trainers'
      fullPath: '/trainers/'
      preLoaderRoute: typeof TrainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$questionId_/edit': {
      id: '/questions/$questionId_/edit'
      path: '/questions/$questionId/edit'
      fullPath: '/questions/$questionId/edit'
      preLoaderRoute: typeof QuestionsQuestionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  OpeningsOpeningIdRoute: OpeningsOpeningIdRoute,
  OpeningsNewRoute: OpeningsNewRoute,
  QuestionsQuestionIdRoute: QuestionsQuestionIdRoute,
  QuestionsNewRoute: QuestionsNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  ConsultationsIndexRoute: ConsultationsIndexRoute,
  OpeningsIndexRoute: OpeningsIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  TrainersIndexRoute: TrainersIndexRoute,
  QuestionsQuestionIdEditRoute: QuestionsQuestionIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
